
DynamicAmbianceDB = {
["probeInstances"] = {
{
["raw"] = {
"Eastern Kingdoms",
"none",
"0",
"",
"0",
"0",
[8] = "0",
[9] = "0",
},
["zone"] = "Elwynn Forest",
["subzone"] = "Northshire Valley",
["isInInstanceType"] = "none",
["groupSize"] = 0,
["passive"] = true,
["realZone"] = "Elwynn Forest",
["IsInRaid"] = "raised",
["groupMembers"] = 0,
["trigger"] = "PLAYER_ENTERING_WORLD",
["UnitInBattleground"] = "raised",
["IsActiveBattlefieldArena"] = "raised",
["IsInGroup"] = "raised",
["difficulty"] = "",
["difficultyID"] = 0,
["name"] = "Eastern Kingdoms",
["instanceType"] = "none",
["when"] = "2026-09-24 18:50:58",
["isInInstance"] = false,
["instanceID"] = 0,
["maxPlayers"] = 0,
},
},
["probeGamma"] = {
["edges"] = {
["finished"] = true,
["clampMax"] = "not reached",
["originalRaw"] = "1.000000",
["rungs"] = {
{
["readBackLater"] = 0.3,
["returned"] = true,
["clamped"] = false,
["wrote"] = 0.3,
["readBack"] = 0.3,
},
{
["readBackLater"] = 0.2,
["returned"] = true,
["clamped"] = false,
["wrote"] = 0.2,
["readBack"] = 0.2,
},
{
["readBackLater"] = 0.1,
["returned"] = true,
["clamped"] = false,
["wrote"] = 0.1,
["readBack"] = 0.1,
},
{
["readBackLater"] = 0.05,
["returned"] = true,
["clamped"] = false,
["wrote"] = 0.05,
["readBack"] = 0.05,
},
{
["readBackLater"] = 0,
["returned"] = true,
["clamped"] = false,
["wrote"] = 0,
["readBack"] = 0,
},
{
["readBackLater"] = -0.5,
["returned"] = true,
["clamped"] = false,
["wrote"] = -0.5,
["readBack"] = -0.5,
},
{
["readBackLater"] = 3,
["returned"] = true,
["clamped"] = false,
["wrote"] = 3,
["readBack"] = 3,
},
{
["readBackLater"] = 3.5,
["returned"] = true,
["clamped"] = false,
["wrote"] = 3.5,
["readBack"] = 3.5,
},
{
["readBackLater"] = 4,
["returned"] = true,
["clamped"] = false,
["wrote"] = 4,
["readBack"] = 4,
},
{
["readBackLater"] = 5,
["returned"] = true,
["clamped"] = false,
["wrote"] = 5,
["readBack"] = 5,
},
{
["readBackLater"] = 7.5,
["returned"] = true,
["clamped"] = false,
["wrote"] = 7.5,
["readBack"] = 7.5,
},
{
["readBackLater"] = 10,
["returned"] = true,
["clamped"] = false,
["wrote"] = 10,
["readBack"] = 10,
},
{
["readBackLater"] = 20,
["returned"] = true,
["clamped"] = false,
["wrote"] = 20,
["readBack"] = 20,
},
{
["readBackLater"] = 50,
["returned"] = true,
["clamped"] = false,
["wrote"] = 50,
["readBack"] = 50,
},
{
["readBackLater"] = 100,
["returned"] = true,
["clamped"] = false,
["wrote"] = 100,
["readBack"] = 100,
},
},
["rejected"] = {
},
["restored"] = {
["value"] = 1,
["when"] = "2026-09-24 18:51:25",
["reason"] = "end of edges",
},
["info"] = {
["storedCharacter"] = false,
["default"] = "1.000000",
["locked"] = false,
["value"] = "1.000000",
["secure"] = false,
["readOnly"] = false,
["storedAccount"] = false,
},
["planned"] = {
0.3,
0.2,
0.1,
0.05,
0,
-0.5,
3,
3.5,
4,
5,
7.5,
10,
20,
50,
100,
},
["when"] = "2026-09-24 18:51:10",
["original"] = 1,
["clampMin"] = "not reached",
["holdSeconds"] = 1,
},
["checks"] = {
{
["ok"] = true,
["name"] = "Gamma is writable",
["detail"] = "value 1.000000 default 1.000000 locked=false secure=false readonly=false",
},
{
["name"] = "clampMin",
["detail"] = "not reached",
},
{
["name"] = "clampMax",
["detail"] = "not reached",
},
{
["ok"] = true,
["name"] = "every edge write went through without raising or returning false",
["detail"] = "15 writes",
},
{
["ok"] = true,
["name"] = "Gamma restored (end of edges)",
["detail"] = "back to 1, was 1",
},
},
},
["persistenceMarker"] = {
["writtenAt"] = "2026-09-24 18:50:57",
["loadCount"] = 1,
},
}
