
DynamicAmbianceDB = {
["probeInstances"] = {
{
["raw"] = {
"Eastern Kingdoms",
"none",
"0",
"",
"0",
"0",
[8] = "0",
[9] = "0",
},
["zone"] = "Elwynn Forest",
["subzone"] = "Northshire Valley",
["isInInstanceType"] = "none",
["groupSize"] = 0,
["passive"] = true,
["realZone"] = "Elwynn Forest",
["IsInRaid"] = "raised",
["groupMembers"] = 0,
["trigger"] = "PLAYER_ENTERING_WORLD",
["UnitInBattleground"] = "raised",
["IsActiveBattlefieldArena"] = "raised",
["IsInGroup"] = "raised",
["difficulty"] = "",
["difficultyID"] = 0,
["name"] = "Eastern Kingdoms",
["instanceType"] = "none",
["when"] = "2026-09-24 18:42:24",
["isInInstance"] = false,
["instanceID"] = 0,
["maxPlayers"] = 0,
},
{
["raw"] = {
"Eastern Kingdoms",
"none",
"0",
"",
"0",
"0",
[8] = "0",
[9] = "0",
},
["zone"] = "Elwynn Forest",
["subzone"] = "Northshire Valley",
["isInInstanceType"] = "none",
["groupSize"] = 0,
["realZone"] = "Elwynn Forest",
["IsInRaid"] = "raised",
["groupMembers"] = 0,
["UnitInBattleground"] = "raised",
["IsActiveBattlefieldArena"] = "raised",
["IsInGroup"] = "raised",
["difficulty"] = "",
["difficultyID"] = 0,
["name"] = "Eastern Kingdoms",
["instanceType"] = "none",
["when"] = "2026-09-24 18:43:28",
["isInInstance"] = false,
["instanceID"] = 0,
["maxPlayers"] = 0,
},
},
["probeGamma"] = {
["finished"] = true,
["ladder"] = {
{
["clamped"] = false,
["readBackLater"] = 0.3,
["wrote"] = 0.3,
["readBack"] = 0.3,
},
{
["clamped"] = false,
["readBackLater"] = 0.5,
["wrote"] = 0.5,
["readBack"] = 0.5,
},
{
["clamped"] = false,
["readBackLater"] = 0.7,
["wrote"] = 0.7,
["readBack"] = 0.7,
},
{
["clamped"] = false,
["readBackLater"] = 0.85,
["wrote"] = 0.85,
["readBack"] = 0.85,
},
{
["clamped"] = false,
["readBackLater"] = 1,
["wrote"] = 1,
["readBack"] = 1,
},
{
["clamped"] = false,
["readBackLater"] = 1.15,
["wrote"] = 1.15,
["readBack"] = 1.15,
},
{
["clamped"] = false,
["readBackLater"] = 1.3,
["wrote"] = 1.3,
["readBack"] = 1.3,
},
{
["clamped"] = false,
["readBackLater"] = 1.5,
["wrote"] = 1.5,
["readBack"] = 1.5,
},
{
["clamped"] = false,
["readBackLater"] = 1.8,
["wrote"] = 1.8,
["readBack"] = 1.8,
},
{
["clamped"] = false,
["readBackLater"] = 2.2,
["wrote"] = 2.2,
["readBack"] = 2.2,
},
{
["clamped"] = false,
["readBackLater"] = 2.6,
["wrote"] = 2.6,
["readBack"] = 2.6,
},
{
["clamped"] = false,
["readBackLater"] = 3,
["wrote"] = 3,
["readBack"] = 3,
},
},
["ladderPlanned"] = {
0.3,
0.5,
0.7,
0.85,
1,
1.15,
1.3,
1.5,
1.8,
2.2,
2.6,
3,
},
["holdSeconds"] = 3,
["readBackMin"] = 0.3,
["restored"] = {
["value"] = 1,
["when"] = "2026-09-24 18:43:08",
["reason"] = "end of ladder",
},
["clampedAt"] = {
},
["info"] = {
["storedCharacter"] = false,
["default"] = "1.000000",
["locked"] = false,
["value"] = "1.000000",
["secure"] = false,
["readOnly"] = false,
["storedAccount"] = false,
},
["originalRaw"] = "1.000000",
["when"] = "2026-09-24 18:42:32",
["original"] = 1,
["checks"] = {
{
["ok"] = true,
["name"] = "Gamma is writable",
["detail"] = "value 1.000000 default 1.000000 locked=false secure=false readonly=false",
},
{
["ok"] = true,
["name"] = "every Gamma rung read back as written",
["detail"] = "12 rungs, 0.30 to 3.00",
},
{
["name"] = "range the client accepted",
["detail"] = "0.3 to 3",
},
{
["ok"] = true,
["name"] = "Gamma restored (end of ladder)",
["detail"] = "back to 1, was 1",
},
},
["readBackMax"] = 3,
},
["probe"] = {
["savedVariables"] = {
["accountStamped"] = {
["writtenAt"] = "2026-09-24 18:42:23",
["loadCount"] = 1,
},
["accountType"] = "nil",
["charStamped"] = {
["writtenAt"] = "2026-09-24 18:42:23",
["loadCount"] = 1,
},
["charType"] = "nil",
["accountWasNil"] = true,
["charWasNil"] = true,
["captured"] = true,
},
["popup"] = {
["defined"] = true,
["shown"] = true,
["hasTable"] = true,
["hasShow"] = true,
},
["finished"] = true,
["checks"] = {
{
["ok"] = false,
["name"] = "account-wide SavedVariables read back",
["detail"] = "arrived nil - write-only, as recorded",
},
{
["ok"] = false,
["name"] = "per-character SavedVariables read back",
["detail"] = "arrived nil",
},
{
["name"] = "  how to read this",
["detail"] = "one run proves nothing. Run the probe, /reload, run it again: if the load # goes up, settings can persist and every toggle asked for is real.",
},
{
["ok"] = true,
["name"] = "C_ChatInfo / SendAddonMessage exists",
["detail"] = "C_ChatInfo.SendAddonMessage",
},
{
["ok"] = true,
["name"] = "prefix 'DynAmb' registered",
["detail"] = "returned 0",
},
{
["ok"] = true,
["name"] = "CHAT_MSG_ADDON registered",
},
{
["ok"] = true,
["name"] = "  send via WHISPER accepted",
},
{
["ok"] = true,
["name"] = "  send via PARTY accepted",
},
{
["ok"] = true,
["name"] = "  send via RAID accepted",
},
{
["ok"] = true,
["name"] = "  send via INSTANCE_CHAT accepted",
},
{
["ok"] = true,
["name"] = "  send via GUILD accepted",
},
{
["ok"] = true,
["name"] = "  send via SAY accepted",
},
{
["name"] = "  delivery",
["detail"] = "counted in 3 seconds - a send that raises nothing may still go nowhere",
},
{
["ok"] = true,
["name"] = "SetItemRef exists",
["detail"] = "the click can be caught",
},
{
["ok"] = true,
["name"] = "a custom link renders in the chat frame",
["detail"] = "click the blue text above - it should NOT open an error",
},
{
["name"] = "  sent to yourself as a whisper",
["detail"] = "watch for it coming back",
},
{
["ok"] = true,
["name"] = "StaticPopupDialogs / StaticPopup_Show exist",
["detail"] = "table present, show present",
},
{
["ok"] = true,
["name"] = "a three-button dialog can be defined",
},
{
["ok"] = true,
["name"] = "StaticPopup_Show accepted it",
["detail"] = "count the buttons - three or two?",
},
{
["name"] = "a dungeon (expected instanceType='party')",
["detail"] = "not yet - the Stormwind Stockade is a ten-minute safe run from Northshire and has no level requirement to enter",
},
{
["name"] = "a raid (expected instanceType='raid')",
["detail"] = "not yet - no walk-in raid is close; let this one arrive on its own",
},
{
["name"] = "a battleground (expected instanceType='pvp')",
["detail"] = "not yet - level 10 for Warsong Gulch on a 1.60-era client",
},
{
["name"] = "epic BG detection rule",
["detail"] = "needs a normal BG and an epic one - unconfirmed until then, and the addon says so rather than guessing retail's bracket",
},
{
["ok"] = true,
["name"] = "an addon message came back",
["detail"] = "1 message(s); channels: WHISPER",
},
{
["name"] = "  longest payload received",
["detail"] = "207 bytes of the 207 sent - intact",
},
},
["when"] = "2026-09-24 18:43:28",
["instanceHere"] = {
["raw"] = {
"Eastern Kingdoms",
"none",
"0",
"",
"0",
"0",
[8] = "0",
[9] = "0",
},
["zone"] = "Elwynn Forest",
["subzone"] = "Northshire Valley",
["isInInstanceType"] = "none",
["groupSize"] = 0,
["realZone"] = "Elwynn Forest",
["IsInRaid"] = "raised",
["groupMembers"] = 0,
["UnitInBattleground"] = "raised",
["IsActiveBattlefieldArena"] = "raised",
["IsInGroup"] = "raised",
["difficulty"] = "",
["difficultyID"] = 0,
["name"] = "Eastern Kingdoms",
["instanceType"] = "none",
["when"] = "2026-09-24 18:43:28",
["isInInstance"] = false,
["instanceID"] = 0,
["maxPlayers"] = 0,
},
["comms"] = {
["received"] = {
{
["sender"] = "<character>",
["prefix"] = "DynAmb",
["payload"] = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA|END200",
["length"] = 207,
["channel"] = "WHISPER",
},
},
["longestReceived"] = 207,
["viaC_ChatInfo"] = true,
["hasSend"] = true,
["eventOK"] = true,
["prefixRegistered"] = true,
["sendAttempts"] = {
{
["target"] = "<character>",
["accepted"] = true,
["channel"] = "WHISPER",
},
{
["accepted"] = true,
["channel"] = "PARTY",
},
{
["accepted"] = true,
["channel"] = "RAID",
},
{
["accepted"] = true,
["channel"] = "INSTANCE_CHAT",
},
{
["accepted"] = true,
["channel"] = "GUILD",
},
{
["accepted"] = true,
["channel"] = "SAY",
},
},
["playerName"] = "<character>",
["hasRegister"] = true,
},
["link"] = {
["sentToSelf"] = true,
["wrapped"] = true,
["printed"] = true,
["hasSetItemRef"] = true,
},
},
["persistenceMarker"] = {
["writtenAt"] = "2026-09-24 18:42:23",
["loadCount"] = 1,
},
}
