-- Dynamic Ambiance - zones. GENERATED by the in-game editor, 2026-09-24 20:00, addon 0.2.0.
-- Read once, on a character's first login, to seed its saved zones; after that the
-- character's saved settings are the zones and this file is not read - except on a build
-- that does not read saved settings back, where it is read at every load. Config.lua holds
-- everything that is not a zone.
local _, ns = ...
local Config = ns.Config
Config.zones = Config.zones or {}

Config.zones["Elwynn Forest"] = {
    contrast = 35,
    brightness = 78,
    map = 1429,
    meta = {
        name = "Elwynn, Northshire test set",
        description = "Proves the addon reacts. Not for looking good.",
        notes = "VALUES ARE DELIBERATELY EXAGGERATED - this set proves the addon reacts; nobody should keep these. Yellow: Elwynn proper (the zone default). Blue: Northshire Valley. Red: every interior, by Config.indoors. EVERY NAME HERE WAS WALKED, not guessed: /amb debug on 2026-09-20 returned Northshire Valley, Main Hall, Hall of Arms, Main Hall, Northshire Valley, nil, Northshire Valley. The nil is the unnamed pocket (purple): no subzone, so it needs a polygon walked in the editor. Map 1429 is measured.",
        version = 1,
        date = "2026-09-24",
    },
    areas = {
        {
            subzone = "Northshire Valley",
            notes = "BLUE. Measured subzone name, from two selftest runs.",
            priority = 10,
            contrast = 55,
            brightness = 45,
        },
        {
            subzone = "Hall of Arms",
            notes = "A room that differs from the indoor rule and outranks it. Gated indoors, so it cannot fire over the same spot outside.",
            priority = 60,
            contrast = 70,
            brightness = 58,
            indoors = true,
        },
        {
            name = "chapel forecourt",
            notes = "Centre: mean of three /amb here captures in the chapel, 2026-09-20. RADII ARE A GUESS - 0.0040/0.0200 normalized, converted to yards by the geometric mean. Outdoors only.",
            x = 0.492,
            y = 0.4143,
            innerYards = 11.3,
            falloffYards = 56.7,
            priority = 20,
            contrast = 85,
            brightness = 25,
            indoors = false,
        },
    },
}

-- end of generated zones
